### ISSUE TITLE
Aki Modulo

### ISSUE THREAD

**Issue by Toskan4134** [MechSlayer/mechmusic#1]
Buenos días, siento molestar por este github, pero no he encontrado ninguna otra forma de contactarte.
Tengo una duda, sobre los idiomas de aki, en especial el "cn", cuando lo he probado me ha dado error, por lo que no funciona, además no existe ningún código ISO (la reduccion para los idiomas) llamada "cn"
¿Me podrías aclarar esta duda por favor?

**Comment by MechSlayer** [comment]
Hola, CN se refiere a CHN que es China, en cuanto al error, seguramente se deba a que los servidores cambian de dirección cada X tiempo. Estoy tratando de automatizar la obtención de los mismos.

**Comment by MechSlayer** [comment]
Solucionado, actualiza a la versión 0.1.1

**Comment by Toskan4134** [comment]
Muchas gracias, por cierto, hay algun sitio por el que te pueda contactar? ya sea discord o algo así

**Comment by MechSlayer** [comment]
MechSlayer#5227
